[package]
name = "bevy_mod_reqwest"
description = "use reqwest with the bevy runtime in the same way on both web and native"
version = "0.10.0"
edition = "2021"
readme = "README.md"
authors = ["Kristoffer Ödmark <kristoffer.odmark90@gmail.com>"]
repository = "https://github.com/TotalKrill/bevy_mod_reqwest.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compat = "0.2.1"
bevy = { version = "0.10.1", default-features = false }
bytes = "=1.1.0"
futures-lite = "1.12.0"
reqwest = "0.11.16"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
[target.'cfg(target_arch = "wasm32")'.dependencies]
crossbeam-channel = "0.5.7"
